// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEpO5vmKCtlVf_RCN3i9EfqtvSJHrXHTg',
    appId: '1:296538534471:web:1af19a10d7bf420d333762',
    messagingSenderId: '296538534471',
    projectId: 'flutter-1-4fd75',
    authDomain: 'flutter-1-4fd75.firebaseapp.com',
    storageBucket: 'flutter-1-4fd75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIqNRk0IZAPXEUYAKFFIoO9z2nFbXSUlI',
    appId: '1:296538534471:android:2220764b22ff932c333762',
    messagingSenderId: '296538534471',
    projectId: 'flutter-1-4fd75',
    storageBucket: 'flutter-1-4fd75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2cisVQKUCqwiiFJfxx2klHtyPYLXKjc',
    appId: '1:296538534471:ios:858230817278307c333762',
    messagingSenderId: '296538534471',
    projectId: 'flutter-1-4fd75',
    storageBucket: 'flutter-1-4fd75.appspot.com',
    iosBundleId: 'com.example.firebasexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI2cisVQKUCqwiiFJfxx2klHtyPYLXKjc',
    appId: '1:296538534471:ios:9bab2b6a3c3f9e39333762',
    messagingSenderId: '296538534471',
    projectId: 'flutter-1-4fd75',
    storageBucket: 'flutter-1-4fd75.appspot.com',
    iosBundleId: 'com.example.firebasexample.RunnerTests',
  );
}
